[package]
name = "rockr"
version = "0.1.0"
edition = "2024"
default-run = "rockrc"

[lib]
bench = false

[dependencies]
clap = "4.5.60"
clap_derive = "4.5.55"
codespan-reporting = "0.13.1"
dashmap = "6.2.1"
ena = "0.14.4"
generativity = "1.2.1"
inkwell = { version = "0.9.0", features = ["llvm22-1"] }
itertools = "0.14.0"
llvm-sys = "221.0.1"
nonempty = "0.12.0"
parking_lot = "0.12.5"
pathdiff = "0.2.3"
regex = "1.12.3"
rustc-literal-escaper = "0.0.7"
salsa = {version = "0.28.0", features = []}
salsa-macros = "0.28.0"
unescaper = "0.1.8"
walkdir = "2.5.0"

[[bin]]
name = "rockrc"
path = "src/compiler/rockrc.rs"

[workspace]
members = ["rockr-lsp"]
