avoid-breaking-exported-api     = false
cognitive-complexity-threshold  = 20
too-many-arguments-threshold    = 100
type-complexity-threshold       = 200
too-many-lines-threshold        = 1000
allow-unwrap-in-tests           = true
allow-expect-in-tests           = true
doc-valid-idents                = ["HIR", "MIR", "AST", "CFG", "SSA", "LLVM", ".."]
